yelp_categories = {'bars':'Bar',
'absinthebars':'Bar',
'airportlounges':'Bar',
'beachbars':'Bar',
'beerbar':'Bar',
'champagne_bars':'Bar',
'cigarbars':'Bar',
'cocktailbars':'Bar',
'divebars':'Bar',
'drivethrubars':'Bar',
'gaybars':'Bar',
'hookah_bars':'Bar',
'hotel_bar':'Bar',
'irish_pubs':'Bar',
'lounges':'Bar',
'pubs':'Bar',
'pulquerias':'Bar',
'sakebars':'Bar',
'speakeasies':'Bar',
'sportsbars':'Bar',
'tabac':'Bar',
'tikibars':'Bar',
'vermouthbars':'Bar',
'whiskeybars':'Bar',
'wine_bars':'Bar',
'fashion':'Fashion Retail',
'accessories':'Fashion Retail',
'ceremonialclothing':'Fashion Retail', 
'childcloth':'Fashion Retail',
'clothingrental':'Fashion Retail',
'deptstores':'Fashion Retail',
'formalwear':'Fashion Retail',
'furclothing':'Fashion Retail',
'hats':'Fashion Retail',
'kimonos':'Fashion Retail',
'leather':'Fashion Retail',
'lingerie':'Fashion Retail',
'maternity':'Fashion Retail',
'menscloth':'Fashion Retail',
'plus_size_fashion':'Fashion Retail',
'shoes':'Fashion Retail',
'sleepwear':'Fashion Retail',
'sportswear':'Fashion Retail',
'dancewear':'Fashion Retail',
'stockings':'Fashion Retail',
'surfshop':'Fashion Retail',
'swimwear':'Fashion Retail',
'tradclothing':'Fashion Retail',
'vintage':'Fashion Retail',
'womenscloth':'Fashion Retail'
}